Bryggrens/Controllers/AboutController.cs
using Bryggrens.Models.ViewModels;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.Extensions.Localization;

namespace Bryggrens.Controllers
{
    public class AboutController : Controller
    {     



        public IActionResult Index()
        {
            var model = new AboutVM
            {
                Name = "Andreas Rydas Rydgren",                
                ProfilePictureUrl = "/images/rydasabout.jpg" 
            };
            return View(model);
        }
    }
}

Bryggrens/Controllers/AspNetUserControllers/LoginController.cs
using Bryggrens.Helpers.Services;
using Bryggrens.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bryggrens.Controllers.AspNetUserControllers
{
    public class LoginController : Controller
    {
        private readonly AuthService _authService;

        public LoginController(AuthService authService)
        {
            _authService = authService;
        }



        public IActionResult Index(string ReturnUrl = null!)
        {
            var viewModel = new UserLoginVM();
            if (ReturnUrl != null)
                viewModel.ReturnUrl = ReturnUrl;
            return View(viewModel);
        }




        //Logga in
        [HttpPost]

        public async Task<IActionResult> Index(UserLoginVM viewModel)
        {
            if (ModelState.IsValid)
            {
                if (await _authService.LoginAsync(viewModel))
                    return LocalRedirect(viewModel.ReturnUrl);
                ModelState.AddModelError("", "Incorrect email or password");
            }

            return View(viewModel);
        }
    }
}

Bryggrens/Controllers/BeerControllers/CategoryController.cs
using Bryggrens.Helpers.Repositories;
using Bryggrens.Helpers.Services;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace Bryggrens.Controllers.BeerControllers
{
    public class CategoryController : Controller
    {
        
        private readonly BeerRepo _beerRepo;

        public CategoryController(BeerRepo beerRepo)
        {
           
            _beerRepo = beerRepo;
        }

        public async Task<IActionResult> Beers()
        {
            var products = await _beerRepo.GetAllAsync();
            return View(products);
        }

        public async Task<IActionResult> FilterByCategory(int categoryId)
        {
            var products = await _beerRepo.GetProductsByCategoryAsync(categoryId);
            return View("Beers", products);
        }



        public async Task<IActionResult> Neipa()
        {
            var neipaCategoryId = 1;
            var products = await _beerRepo.GetProductsByCategoryAsync(neipaCategoryId);
            return View(products);
        }

        public async Task<IActionResult> Sour()
        {
            var sourCategoryId = 2;
            var products = await _beerRepo.GetProductsByCategoryAsync(sourCategoryId);
            return View(products);
        }



        public async Task<IActionResult> PaleAle()
        {
            var paleAleCategoryId = 3;
            var products = await _beerRepo.GetProductsByCategoryAsync(paleAleCategoryId);
            return View(products);
        }



    }
}

Bryggrens/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bryggrens.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult ThankYouView()
        {
            return View();
        }
    }
}

Bryggrens/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bryggrens.Controllers
{
    public class EventsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bryggrens/Views/Partials/_About.cshtml
@model AboutVM

<section class="about">
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-6">
                <div class="image-container">
                    <img src="@Model.ProfilePictureUrl" alt="Profile Picture" class="about-image">
                    <div class="image-overlay"></div>
                </div>
                <ul class="info-list">
                    <li><i class="fas fa-star"></i> Award-winning brewer</li>
                    <li><i class="fas fa-beer"></i> Craft beer enthusiast</li>
                    <li><i class="fas fa-globe"></i> Beer connoisseur with international experience</li>
                    <li><i class="fas fa-trophy"></i> Champion of local beer competitions</li>
                </ul>
            </div>
            <div class="col-md-6">                
                <h3>@Model.Name</h3>
                <p class="about-description">
                    @Model.GetRydasDescription()
                </p>
                
            </div>
        </div>
    </div>
</section>



    <div class="container about-container">
       

        <div class="about-buttons">
            <button id="missionBtn" class="active" onclick="toggleContent('mission')">Mission and Values</button>
            <button id="brewingBtn" onclick="toggleContent('brewing')">Brewing Process</button>
        </div>

        <div id="missionContent">
        
            At Bryggrens, we are not only passionate about crafting exceptional beers but also share a deep love for Everton Football Club. Our mission is to brew outstanding beers that unite beer enthusiasts and Everton fans alike, celebrating the spirit of the club and creating unforgettable experiences.
            Our values align with the Evertonian ethos, and we are proud to embody the following principles:
        <ul>
            <li><b>Quality:</b> Just like the dedication and precision exhibited on the football pitch, we are committed to brewing beers of the highest quality. Our attention to detail ensures that every sip delivers a winning taste.</li>
            <li><b>Community:</b> We believe in the power of community, both on and off the field. As Evertonians, we are passionate about fostering a sense of togetherness and camaraderie among our fellow fans and beer enthusiasts. We actively engage with the Everton community and contribute to local initiatives that make a positive impact.</li>
            <li><b>Innovation:</b> Similar to Everton's history of pioneering football strategies, we embrace innovation in brewing. We continuously explore new flavors, techniques, and beer styles, pushing boundaries and providing our customers with innovative brews that excite their taste buds.</li>
            <li><b>Heritage:</b> Everton has a rich heritage and a loyal fanbase, and we celebrate this legacy in our brewery. We draw inspiration from the club's history, traditions, and iconic moments to create beers that pay homage to Everton's spirit and resonate with Evertonians worldwide.</li>
      
        </ul>
        <p>By intertwining the worlds of football and brewing, we aim to create a unique experience for Everton fans, beer enthusiasts, and the broader community. Join us in raising a glass to the Toffees and the pursuit of great beer!</p>
        </div>

        <div id="brewingContent" style="display: none;">
        At Bryggrens, our brewing process is a labor of love. We start with carefully selected ingredients, 
        brewing with meticulous attention to detail. From mashing to fermentation and conditioning, 
        we create exceptional beers that embody our commitment to quality and innovation. 
        Each sip of Bryggrens beer is a testament to our passion and craftsmanship, delivering an unforgettable drinking experience.
        </div>
    </div>

Bryggrens/Views/Partials/_BeerCarousel.cshtml
<section class="beer-carousel">
    <div class="container">
        <div class="carousel-header">
            <h1 class="carousel-title">Discover the Bryggrens Experience: Where Adventure Meets Exceptional Beer</h1>
            <p class="carousel-description">Embark on an adventure through our handcrafted collection of artisanal craft beers. Immerse yourself in a world of unique flavors, hoppy delights, and refreshing brews. Discover the perfect brew to satisfy your taste buds and elevate your beer experience. Cheers to a journey of exceptional craftsmanship and the art of brewing!</p>
        </div>
        <div class="carousel">
            <button class="carousel-prev slick-prev"><i class="fas fa-chevron-left"></i></button>
            <div class="carousel-items">
                <div class="carousel-item">
                    <img src="/images/sour-beers.jpg" alt="Banner 1">
                </div>
                <div class="carousel-item">
                    <img src="/images/sour-beers.jpg" alt="Banner 2">
                </div>
                <div class="carousel-item">
                    <img src="/images/sour-beers.jpg" alt="Banner 3">
                </div>
                <!-- Add more carousel items with different banners -->
            </div>
            <button class="carousel-next slick-next"><i class="fas fa-chevron-right"></i></button>
        </div>
    </div>
</section>

Bryggrens/Views/Partials/_BeerSelection.cshtml
<section class="beer-selection">
    <div class="container">
        <h2>Our Beer Selection</h2>


        <div class="beer-list">
            <a class="beer-item" asp-controller="Category" asp-action="Neipa">
                <img src="/images/neipa.jpg" alt="Beer 1">
                <h3>NEIPA Beer</h3>
                <p>A hazy and juicy IPA with tropical hop flavors and a smooth mouthfeel.</p>
            </a>
            <a class="beer-item" asp-controller="Category" asp-action="Sour">
                <img src="/images/sour-beers.jpg" alt="Beer 2">
                <h3>Sour Beer</h3>
                <p>A tart and refreshing beer with a tangy, acidic flavor profile and hints of fruit or funkiness.</p>

            </a>
            <a class="beer-item" asp-controller="Category" asp-action="PaleAle">
                <img src="/images/paleale.jpg" alt="Beer 3">
                <h3>Pale Ale</h3>
                <p>A balanced and hop-forward beer with a crisp and malty profile, showcasing citrusy or floral hop flavors.</p>
            </a>
            <!-- Add more beer items with different categories -->
        </div>

        <h5>Not sure what you are looking for specifically? <a asp-controller="Category" asp-action="Beers">Click here to show all our beers</a></h5>
    </div>
</section>

Bryggrens/Views/Partials/_ContactForm.cshtml
@model ContactFormVM
@{
    ViewData["Title"] = "Contact us!";
}

<section class="contact-form">
    <div class="container">
        <form method="post" asp-controller="Contacts" asp-action="ThankYouView" novalidate>
            <div asp-validation-summary="ModelOnly" class="form-group error"></div>

            <div class="name form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name"/>
                <span asp-validation-for="Name" class="error"></span>
            </div>

            <div class="email form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email"/>
                <span asp-validation-for="Email" class="error"></span>
            </div>

            <div class="phoneNumber form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" />
                <span asp-validation-for="PhoneNumber" class="error"></span>
            </div>

            <div class="companyName form-group">
                <label asp-for="Company"></label>
                <input asp-for="Company" />
                <span asp-validation-for="Company" class="error"></span>
            </div>

            <div class="message form-group">
                <label asp-for="Comment"></label>
                <textarea id="Comment" asp-for="Comment"></textarea>
                <span asp-validation-for="Comment" class="error"></span>
            </div>

            <div class="terms form-checkbox-group">
                <label class="custom-checkbox">
                    <label asp-for="SaveMyData"></label>
                    <input asp-for="SaveMyData" />
                    <span class="checkmark"></span>
                </label>
                <span asp-validation-for="SaveMyData" class="error"></span>
            </div>

            <button class="btn-everton"><i class="fas fa-beer"></i>Submit</button>
        </form>
    </div>
</section>

Bryggrens/Views/Partials/_Footer.cshtml
<footer class="footer">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="https://www.facebook.com/brewery" target="_blank"><i class="fab fa-facebook"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://www.instagram.com/brewery" target="_blank"><i class="fab fa-instagram"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://twitter.com/brewery" target="_blank"><i class="fab fa-twitter"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</footer>

Bryggrens/Views/Partials/_Header.cshtml
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container mb-3">
        <a class="navbar-brand" href="/">Bryggrens</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
                <!-- mx-auto centrera elementen -->
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        About
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="About" asp-action="Index">About Us</a>                        
                        <a class="dropdown-item" asp-controller="Events" asp-action="Index">Events</a>
                        <a class="dropdown-item" asp-controller="Locations" asp-action="Index">Locations</a>
                        <a class="dropdown-item" asp-controller="Tours" asp-action="Index">Brewery Tours</a>
                        <a class="dropdown-item" asp-controller="Blog" asp-action="Index">Blog/News</a>
                    </div>
                </li>


                <li class="nav-item">
                    <a class="nav-link" asp-controller="Contacts" asp-action="Index">Contact us</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <!-- ml-auto för att placera elementen till höger -->
                @if (signInManager.IsSignedIn(User))
                {
                    var user = await userManager.GetUserAsync(User);

                    if (user != null)
                    {
                        if (await userManager.IsInRoleAsync(user, "admin"))
                        {
                            <a class="nav-link" asp-controller="admin" asp-action="Index" class="link">Admin</a>
                        }
                        else
                        {
                            <a class="link" asp-controller="Account" asp-action="Index">@User.Identity?.Name</a>
                        }
                    }

                    <a class="nav-link" asp-controller="logout" asp-action="Index" class="link">Logout</a>
                }
                else
                {
                    <a class="nav-link" asp-controller="Login" asp-action="Index" class="link">Login</a>
                }
            </ul>
        </div>
    </div>
</nav>

Bryggrens/Views/Partials/_Neipa.cshtml
<div id="productList">
    
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <img src="~/images/neipa.jpg" alt="@product.BeerName" style="height:270px; width:270px;"> <!-- Funkar inte -->
                    <div class="card-body">
                        <h5 class="card-title">Name: @product.BeerName</h5>
                        <p class="card-text">Articlenumber: @product.ArticleNumber</p>
                        <p class="card-text">Description : @product.BeerDescription</p>
                        <p class="card-text">Alcohol: @product.AlcoholPercent%</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Bryggrens/Views/Partials/_PaleAle.cshtml
<div id="productList">
   
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <img src="~/images/paleale.jpg" alt="@product.BeerName" style="height:270px; width:270px;"> <!-- Funkar inte -->
                    <div class="card-body">
                        <h5 class="card-title">Name: @product.BeerName</h5>
                        <p class="card-text">Articlenumber: @product.ArticleNumber</p>
                        <p class="card-text">Description : @product.BeerDescription</p>
                        <p class="card-text">Alcohol: @product.AlcoholPercent%</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Bryggrens/Views/Partials/_PopupBox.cshtml
<div id="popup-box" class="hidden">
    <div class="popup-content">
        <h2>WOO WOO WOO</h2>
        <p>Be sure to check out our events! There could be one near you!</p>
        <a class="btn-everton" asp-controller="Events" asp-action="Index">Check Out Our Events!</a>       
    </div>
</div>

Bryggrens/Views/Partials/_ShowAllBeers.cshtml
<div class="container">
    <div class="beer-categories mt-4">
        <button class="active" data-category="all" onclick="filterProducts('all')">All</button>
        <button data-category="1" onclick="filterProducts(1)">NEIPA</button>
        <button data-category="2" onclick="filterProducts(2)">Sour</button>
        <button data-category="3" onclick="filterProducts(3)">Pale Ale</button>
    </div>


    <div id="productList">
       
        <div class="row mt-5">
            @foreach (var product in Model)
            {
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <img src="~/images/@product.ImageUrl" alt="@product.BeerName" style="height:270px; width:270px;"> <!-- Funkar inte -->
                        <div class="card-body">
                            <h5 class="card-title">Name: @product.BeerName</h5>
                            <p class="card-text">Articlenumber: @product.ArticleNumber</p>
                            <p class="card-text">Description : @product.BeerDescription</p>
                            <p class="card-text">Alcohol: @product.AlcoholPercent%</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Bryggrens/Views/Partials/_Sour.cshtml
<div id="productList">
   
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <img src="~/images/sour-beers.jpg" alt="@product.BeerName" style="height:270px; width:270px;"> <!-- Funkar inte -->
                    <div class="card-body">
                        <h5 class="card-title">Name: @product.BeerName</h5>
                        <p class="card-text">Articlenumber: @product.ArticleNumber</p>
                        <p class="card-text">Description : @product.BeerDescription</p>
                        <p class="card-text">Alcohol: @product.AlcoholPercent%</p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Bryggrens/Views/Partials/_VideoShowcase.cshtml
<section class="showcase">
    
        <div class="video-showcase">
        <video id="showcaseVideo" src="/images/videos/_videoshowcase.mp4" autoplay muted controls loop></video>
        </div>
    
</section>